services:

  # MySQL Database
  db:
    image: mysql:latest
    container_name: photocloud-mysql
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: 2a44c03a7ce03c20efb5bdbdbc229725
      MYSQL_DATABASE: photocloud
      MYSQL_USER: user
      MYSQL_PASSWORD: 058162440502fffff96cb244bb739c80
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

# Persist MySQL Data
volumes:
  db_data: